### ISSUE TITLE
Font Nunito

### ISSUE THREAD

**Issue by Terra42** [MonikaVrsecka/PROJEKT-Vizitka#2]
https://github.com/MonikaVrsecka/PROJEKT-Vizitka/blob/1702222f28570e22e4b3a8630e3d567ffdec3d15/index.html#L7

Chybí ti font Nunito, který je v zadání. Nepodařilo se ti ho přes Google Fonts nalinkovat?

**Comment by MonikaVrsecka** [comment]
Neměla jsem ho přidaný v HTML body části. Teď už by mělo být ok.

**Comment by Terra42** [comment]
Super! :)
